package com.mo.tile.bean;

import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * @TableName batch
 */
@Data
public class Batch implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table batch
     *
     * @mbg.generated Fri Jan 15 17:30:29 CST 2021
     */
    private static final long serialVersionUID = 1L;
    /**
     * @mbg.generated Fri Jan 15 17:30:29 CST 2021
     */

    @TableId("batch_id")
    private Integer batch_id;
    /**
     * @mbg.generated Fri Jan 15 17:30:29 CST 2021
     */
    private Date batch_creation;
    /**
     * @mbg.generated Fri Jan 15 17:30:29 CST 2021
     */
    private Date batch_completion;
    /**
     * @mbg.generated Fri Jan 15 17:30:29 CST 2021
     */
    private Integer batch_product_type;
    /**
     * @mbg.generated Fri Jan 15 17:30:29 CST 2021
     */
    private Integer batch_total;

    /**
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Batch other = (Batch) that;
        return (this.getBatch_id() == null ? other.getBatch_id() == null : this.getBatch_id().equals(other.getBatch_id()))
                && (this.getBatch_creation() == null ? other.getBatch_creation() == null : this.getBatch_creation().equals(other.getBatch_creation()))
                && (this.getBatch_completion() == null ? other.getBatch_completion() == null : this.getBatch_completion().equals(other.getBatch_completion()))
                && (this.getBatch_product_type() == null ? other.getBatch_product_type() == null : this.getBatch_product_type().equals(other.getBatch_product_type()))
                && (this.getBatch_total() == null ? other.getBatch_total() == null : this.getBatch_total().equals(other.getBatch_total()));
    }

    /**
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBatch_id() == null) ? 0 : getBatch_id().hashCode());
        result = prime * result + ((getBatch_creation() == null) ? 0 : getBatch_creation().hashCode());
        result = prime * result + ((getBatch_completion() == null) ? 0 : getBatch_completion().hashCode());
        result = prime * result + ((getBatch_product_type() == null) ? 0 : getBatch_product_type().hashCode());
        result = prime * result + ((getBatch_total() == null) ? 0 : getBatch_total().hashCode());
        return result;
    }

    /**
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", batch_id=").append(batch_id);
        sb.append(", batch_creation=").append(batch_creation);
        sb.append(", batch_completion=").append(batch_completion);
        sb.append(", batch_product_type=").append(batch_product_type);
        sb.append(", batch_total=").append(batch_total);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}