package com.mo.tile.bean;

import com.baomidou.mybatisplus.annotation.TableId;
import lombok.Data;

import java.io.Serializable;

/**
 * @TableName products
 */
@Data
public class Products implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table products
     *
     * @mbg.generated Thu Jan 14 23:55:28 CST 2021
     */
    private static final long serialVersionUID = 1L;
    /**
     * @mbg.generated Thu Jan 14 23:55:28 CST 2021
     */
    @TableId("product_id")
    private Integer product_id;
    /**
     * @mbg.generated Thu Jan 14 23:55:28 CST 2021
     */
    private Integer product_type;
    /**
     * @mbg.generated Thu Jan 14 23:55:28 CST 2021
     */
    private String product_batch;
    /**
     * @mbg.generated Thu Jan 14 23:55:28 CST 2021
     */
    private Integer product_places;
    /**
     * @mbg.generated Thu Jan 14 23:55:28 CST 2021
     */
    private Integer product_price;
    /**
     * @mbg.generated Thu Jan 14 23:55:28 CST 2021
     */
    private String product_code;
}